function MyObj() { }
MyObj.prototype.z = 3;
var obj = new MyObj();
obj.x = 1;
obj.y = 2;
console.log(obj.x);
console.log(obj.y);
console.log(obj.z);
console.log("z" in obj);
console.log(obj.hasOwnProperty("z"));
obj.z = 5;
obj.hasOwnProperty("z");
console.log(obj.z);
console.log(MyObj.prototype.z);
obj.z = 8;
console.log(obj.z);
delete obj.z;
console.log(obj.z);
delete obj.z;
console.log(obj.z);
delete  obj.__proto__.z;
console.log(obj.z);